name: Cinema Star
options:
  minimumXcodeGenVersion: 2.3.0
  deploymentTarget:
    iOS: 15.0
  groupSortPosition: top
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 3
  bundleIdPrefix: "-.Cinema Star"
packages:
  SwiftKeychainWrapper:
    url: https://github.com/jrendel/SwiftKeychainWrapper
    majorVersion: 4.0.1
targets:
  Cinema Star:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Cinema Star
    dependencies:
      - package: SwiftKeychainWrapper
    settings:
        base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "15.0"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
    postCompileScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then
                "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
